version: '3'

services:
  api:
    image: antonstjernquist/resources-api:main
    environment:
      - BASE_URL
      - DB_CONNECTION_STRING
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - JWT_SECRET
      - PAYPAL_BASE_URL
      - PAYPAL_CLIENT_ID
      - PAYPAL_SECRET_ID
      - S3_ACCESS_KEY
      - S3_BUCKET_NAME
      - S3_ENDPOINT
      - S3_SECRET_KEY
      - SITE_URL
    ports: #make db accessible locally
      - '0.0.0.0:4000:4000'
